name: newsapi
description: Use the NewsApi v2 service in Dart. The library has a clear return structure and an easy-to-use API.
version: 1.0.8
homepage: https://github.com/YeungKC/NewsApi

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  pretty_dio_logger: ^1.1.1
  retrofit: ^1.3.4
  equatable: ^1.2.2
  json_annotation: ^3.0.1

dev_dependencies:
  retrofit_generator: ^1.3.7+4
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  test: ^1.15.3
  pedantic: ^1.9.2
