name: newsapi
description: Use the NewsApi v2 service in Dart. The library has a clear return structure and an easy-to-use API.
version: 1.0.2
homepage: https://github.com/YeungKC/NewsApi

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  pretty_dio_logger: ^1.1.1
  retrofit: ^1.3.1+1
  equatable: ^1.1.1
  json_annotation: ^3.0.0

dev_dependencies:
  retrofit_generator: ^1.3.1+9
  build_runner: ^1.8.0
  json_serializable: ^3.2.0
  test: ^1.6.0
